import Link from "next/link";

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center px-4">
      <div className="text-center max-w-2xl">
        <div className="inline-block bg-brand/10 border border-brand/20 text-brand text-sm font-medium px-4 py-1.5 rounded-full mb-6">
          AI-Powered Resume Builder
        </div>
        <h1 className="text-5xl font-extrabold text-white mb-4 tracking-tight">
          Resumes that get you <span className="text-brand">hired</span>
        </h1>
        <p className="text-gray-400 text-lg mb-10 leading-relaxed">
          Tailored resumes, cover letters, and portfolios generated by AI in seconds.
          Built for students and early-career professionals.
        </p>
        <div className="flex gap-4 justify-center">
          <Link
            href="/register"
            className="btn-primary text-base px-8 py-3"
          >
            Get started free
          </Link>
          <Link
            href="/login"
            className="border border-surface-border text-gray-300 hover:text-white hover:border-gray-400 font-semibold px-8 py-3 rounded-lg transition-colors duration-200 text-base"
          >
            Sign in
          </Link>
        </div>
      </div>
    </main>
  );
}
